import React, { useState, useEffect, useRef } from 'react';
import { 
  Camera, 
  Video, 
  Square, 
  Save, 
  XCircle, 
  RotateCcw, 
  CheckCircle2, 
  AlertTriangle, 
  Wrench, 
  Building2, 
  Flame, 
  Cpu, 
  FileCheck, 
  Sparkles, 
  Eye, 
  Maximize2, 
  Clock, 
  MapPin, 
  Check, 
  X,
  Play,
  Pause,
  Film
} from 'lucide-react';
import { DepartmentRole, MonitoringSession, RecordedVideoSession } from '../types';
import { DEPARTMENTS_METADATA } from '../data/departmentCustomFields';
import { addVideoToArchive, logDepartmentActivity } from '../data/authCredentials';

interface DepartmentDedicatedCameraModalProps {
  isOpen: boolean;
  department: DepartmentRole;
  onClose: () => void;
  onSaveSession?: (session: MonitoringSession) => void;
  defaultLocationName?: string;
  activeSession?: MonitoringSession | null;
}

export const DepartmentDedicatedCameraModal: React.FC<DepartmentDedicatedCameraModalProps> = ({
  isOpen,
  department,
  onClose,
  onSaveSession,
  defaultLocationName = 'محطة كارجاس - الموقع الميداني',
  activeSession,
}) => {
  const meta = DEPARTMENTS_METADATA[department] || DEPARTMENTS_METADATA.operations;

  // Session parameters
  const [siteName, setSiteName] = useState(defaultLocationName);
  const [governorate, setGovernorate] = useState('القاهرة');
  const [sessionStartTime] = useState<Date>(new Date());
  const [durationSeconds, setDurationSeconds] = useState(0);
  const [isRecording, setIsRecording] = useState(true);
  const [inspectedItems, setInspectedItems] = useState<string[]>([]);
  const [selectedFindings, setSelectedFindings] = useState<string[]>([]);
  const [findingsNotes, setFindingsNotes] = useState('');
  const [showCancelConfirm, setShowCancelConfirm] = useState(false);

  const videoRef = useRef<HTMLVideoElement>(null);
  const [cameraStreamActive, setCameraStreamActive] = useState(false);
  const [cameraError, setCameraError] = useState(false);

  // Format time for session naming
  const formatTimeName = (date: Date) => {
    const d = date.toLocaleDateString('ar-EG', { year: 'numeric', month: '2-digit', day: '2-digit' });
    const t = date.toLocaleTimeString('ar-EG', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true });
    return `${d} - ${t}`;
  };

  const autoGeneratedTitle = `جلسة رصد وتوثيق (${formatTimeName(sessionStartTime)}) - ${meta.title}`;

  // Department-specific inspection checklist items
  const getDepartmentEquipments = (): { id: string; label: string }[] => {
    switch (department) {
      case 'operations':
        return [
          { id: 'compressor', label: 'ضاغط الغاز الرئيسي (Compressor)' },
          { id: 'dispenser', label: 'موزعات الغاز والطلمبات (Dispensers)' },
          { id: 'cascades', label: 'اسطوانات التخزين وبنوك الغاز (Cascades)' },
          { id: 'pressure_gauges', label: 'عدادات الضغط والحرارة' },
          { id: 'cooling_system', label: 'نظام التبريد ومراوح التهوية' },
          { id: 'control_panel', label: 'لوحة التحكم الكهربائية والمراقبة' },
        ];
      case 'projects':
        return [
          { id: 'land_leveling', label: 'تسوية الأرض ومناسيب الموقع' },
          { id: 'concrete_bases', label: 'القواعد الخرسانية المسلحة للضاغط' },
          { id: 'canopy_structure', label: 'الهيكل المعدني والجمالونات للمظلة' },
          { id: 'boundary_wall', label: 'السور الخارجي وبوابات الدخول والخروج' },
          { id: 'sales_building', label: 'مبنى المبيعات والتحكم' },
          { id: 'pavement', label: 'أرضيات الهليكوبتر وأعمال الرصف' },
        ];
      case 'hse':
        return [
          { id: 'gas_detectors', label: 'كواشف الغاز الطبيعي (Gas Detectors)' },
          { id: 'flame_detectors', label: 'كواشف اللهب والأشعة UV/IR' },
          { id: 'esd_valve', label: 'صمام الغلق في الطوارئ (Emergency Shutdown ESD)' },
          { id: 'fire_extinguishers', label: 'طفايات الحريق ومدافع المسحوق الجاف' },
          { id: 'safety_distances', label: 'فحص مسافات الأمان NFPA 52' },
          { id: 'emergency_exits', label: 'مخارج الطوارئ وممرات الإخلاء' },
        ];
      case 'technical':
        return [
          { id: 'prs_station', label: 'محطة تخفيض الضغط والقياس (PRS)' },
          { id: 'pipeline_tie_in', label: 'نقطة الربط على خط الغاز الرئيسي' },
          { id: 'flow_meters', label: 'عدادات قياس التدفق والحجم' },
          { id: 'pressure_tests', label: 'اختبارات ضغوط النيتروجين والغاز' },
          { id: 'valves_skid', label: 'منظومة المحابس والفلترة' },
        ];
      default:
        return [
          { id: 'site_survey', label: 'معاينة الموقع ومطابقة المخطط الهندسي' },
          { id: 'surrounding_roads', label: 'الشوارع المحيطة والمداخل والمخارج' },
          { id: 'official_documents', label: 'توثيق لوحات التراخيص والحدود' },
        ];
    }
  };

  // Timer effect
  useEffect(() => {
    if (!isOpen) return;
    let timer: NodeJS.Timeout;
    if (isRecording) {
      timer = setInterval(() => {
        setDurationSeconds(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(timer);
  }, [isOpen, isRecording]);

  // Request actual camera stream if permitted
  useEffect(() => {
    if (!isOpen) return;

    let localStream: MediaStream | null = null;
    navigator.mediaDevices?.getUserMedia({ video: { facingMode: 'environment' }, audio: false })
      .then(stream => {
        localStream = stream;
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
          videoRef.current.play().catch(() => {});
          setCameraStreamActive(true);
        }
      })
      .catch(() => {
        setCameraError(true);
        setCameraStreamActive(false);
      });

    return () => {
      if (localStream) {
        localStream.getTracks().forEach(track => track.stop());
      }
    };
  }, [isOpen]);

  if (!isOpen) return null;

  const toggleInspectedItem = (label: string) => {
    if (inspectedItems.includes(label)) {
      setInspectedItems(inspectedItems.filter(i => i !== label));
    } else {
      setInspectedItems([...inspectedItems, label]);
    }
  };

  // Action: Finish and Save Session
  const handleFinishAndSave = () => {
    setIsRecording(false);

    const sessionId = 'doc-' + Date.now().toString(36);
    const timeDisplay = formatTimeName(sessionStartTime);

    // Create session record
    const newSession: MonitoringSession = {
      id: sessionId,
      code: 'CARGAS-DOC-' + Math.floor(1000 + Math.random() * 9000),
      title: autoGeneratedTitle,
      locationName: siteName,
      governorate: governorate,
      city: 'المنطقة الميدانية',
      coordinates: activeSession?.coordinates || { lat: 30.0444, lng: 31.2357 },
      nearestStation: siteName,
      trafficDirection: 'توثيق هندسي وميداني للإدارة',
      surveyorName: meta.title,
      status: 'completed',
      startTime: sessionStartTime.toISOString(),
      endTime: new Date().toISOString(),
      durationSeconds: durationSeconds || 60,
      counts: {
        private: 0,
        taxi: 0,
        microbus: 0,
        van: 0,
        minibus: 0,
        pickup: 0,
        bus: 0,
        motorcycle: 0,
        suzuki_van: 0,
        peugeot_station: 0
      },
      detections: [],
      departmentOrigin: department,
      documentationCategory: department === 'operations' ? 'equipment_machinery' :
                             department === 'projects' ? 'land_civil' :
                             department === 'hse' ? 'safety_inspection' :
                             department === 'technical' ? 'technical_network' : 'traffic_census',
      videoDurationSeconds: durationSeconds || 60,
      notes: findingsNotes || `تم توثيق ${inspectedItems.length} عنصر من عناصر ${meta.title} بنجاح.`
    };

    // Store in video archive
    const videoArchiveItem: RecordedVideoSession = {
      id: 'vid-' + Date.now().toString(36),
      sessionId: newSession.id,
      sessionTitle: newSession.title,
      department: department,
      departmentName: meta.title,
      locationName: siteName,
      governorate: governorate,
      recordedBy: `${meta.badge} - مسؤول الرصد والتوثيق`,
      recordedAt: sessionStartTime.toISOString(),
      timestampDisplay: timeDisplay,
      durationSeconds: durationSeconds || 60,
      category: newSession.documentationCategory || 'equipment_machinery',
      categoryLabel: `رصد وتوثيق: ${meta.title}`,
      thumbnailUrl: department === 'operations' 
        ? 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80'
        : department === 'projects'
        ? 'https://images.unsplash.com/photo-1541888946425-d0fbb1861563?w=800&auto=format&fit=crop&q=80'
        : 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&auto=format&fit=crop&q=80',
      equipmentInspected: inspectedItems.length > 0 ? inspectedItems : ['معاينة وتوثيق الموقع كاملاً'],
      findingsSummary: findingsNotes || 'تم استكمال التوثيق الميداني وحفظ الفيديو بجودة فائقة في مخزن الإدارة ومدير النظام.',
      fileSizeBytes: (durationSeconds || 60) * 180000
    };

    addVideoToArchive(videoArchiveItem);

    // Log this activity
    logDepartmentActivity({
      department: department,
      departmentName: meta.title,
      actorName: `${meta.badge} (المدير العام)`,
      actorRole: 'general_manager',
      actionType: 'camera_session_saved',
      title: `حفظ وتوثيق جلسة رصد: ${newSession.title}`,
      details: `تم إنهاء وحفظ جلسة الرصد الميداني في ${siteName} بمدة ${Math.floor(durationSeconds / 60)} دقيقة و ${durationSeconds % 60} ثانية وتخزين الفيديو في الأرشيف المركزي.`,
      relatedSessionId: sessionId
    });

    if (onSaveSession) {
      onSaveSession(newSession);
    }
    onClose();
  };

  // Action: Cancel Saving
  const handleCancelSaving = () => {
    setShowCancelConfirm(false);
    onClose();
  };

  const minutes = Math.floor(durationSeconds / 60);
  const seconds = durationSeconds % 60;
  const timeFormatted = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-slate-950/90 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-5xl max-h-[96vh] flex flex-col bg-slate-900 border border-slate-700 rounded-3xl overflow-hidden shadow-2xl">
        
        {/* Top Bar with Title and Exact Time */}
        <div className="p-4 sm:p-5 bg-slate-950 border-b border-slate-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 shrink-0">
              <Camera className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-black text-white">
                  كاميرا الرصد والتوثيق الميداني المباشر
                </h3>
                <span className="px-2 py-0.5 rounded-full text-[11px] font-bold bg-slate-800 text-slate-300 border border-slate-700">
                  {meta.title}
                </span>
              </div>
              <p className="text-xs text-emerald-400 font-mono flex items-center gap-1.5 mt-0.5">
                <Clock className="w-3.5 h-3.5" />
                <span>تسمية الجلسة المعتمدة: {autoGeneratedTitle}</span>
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 self-end sm:self-auto">
            {/* Live REC badge */}
            <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-red-500/20 border border-red-500/40 text-red-400 text-xs font-mono font-bold">
              <span className="w-2.5 h-2.5 rounded-full bg-red-500 animate-ping" />
              <span>تسجيل حي: {timeFormatted}</span>
            </div>
            <button
              onClick={() => setShowCancelConfirm(true)}
              className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition-colors"
              title="إغلاق"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Camera View Area (7 Cols) */}
          <div className="lg:col-span-7 flex flex-col gap-4">
            <div className="relative aspect-video w-full rounded-2xl bg-black border border-slate-800 overflow-hidden shadow-inner flex items-center justify-center">
              
              {/* Actual stream or Simulation visual */}
              {cameraStreamActive ? (
                <video
                  ref={videoRef}
                  autoPlay
                  playsInline
                  muted
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="relative w-full h-full">
                  <img
                    src={department === 'operations' 
                      ? 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&auto=format&fit=crop&q=80'
                      : department === 'projects'
                      ? 'https://images.unsplash.com/photo-1541888946425-d0fbb1861563?w=1200&auto=format&fit=crop&q=80'
                      : 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=1200&auto=format&fit=crop&q=80'
                    }
                    alt="Camera feed"
                    className="w-full h-full object-cover opacity-80"
                  />
                  {/* Grid Lines Overlay */}
                  <div className="absolute inset-0 grid grid-cols-3 grid-rows-3 pointer-events-none border border-white/10">
                    <div className="border-r border-b border-white/10" />
                    <div className="border-r border-b border-white/10" />
                    <div className="border-b border-white/10" />
                    <div className="border-r border-b border-white/10" />
                    <div className="border-r border-b border-white/10" />
                    <div className="border-b border-white/10" />
                    <div className="border-r border-white/10" />
                    <div className="border-r border-white/10" />
                    <div />
                  </div>
                </div>
              )}

              {/* HUD Overlays */}
              <div className="absolute top-3 right-3 flex items-center gap-2">
                <div className="px-2.5 py-1 rounded-lg bg-black/60 backdrop-blur-sm text-white font-mono text-[11px] border border-white/10">
                  1080P HD • 30 FPS • CARGAS NGV
                </div>
                <div className={`px-2.5 py-1 rounded-lg backdrop-blur-sm font-mono text-[11px] border flex items-center gap-1.5 ${
                  isRecording 
                    ? 'bg-rose-950/80 text-rose-300 border-rose-500/30' 
                    : 'bg-amber-950/80 text-amber-300 border-amber-500/30'
                }`}>
                  <span className={`w-2 h-2 rounded-full ${isRecording ? 'bg-rose-500 animate-ping' : 'bg-amber-500'}`}></span>
                  <span>{isRecording ? 'تسجيل مباشر' : 'متوقف مؤقتاً'}</span>
                </div>
              </div>
              <div className="absolute top-3 left-3 px-2.5 py-1 rounded-lg bg-black/60 backdrop-blur-sm text-emerald-400 font-mono text-[11px] border border-emerald-500/20">
                {timeFormatted}
              </div>
              <div className="absolute bottom-3 right-3 px-3 py-1.5 rounded-lg bg-black/70 backdrop-blur-sm text-white text-xs border border-white/10 max-w-[80%] truncate">
                {siteName} • {governorate}
              </div>

              {/* Floating Quick Pause / Resume Button on Video */}
              <button
                type="button"
                onClick={() => setIsRecording(!isRecording)}
                title={isRecording ? "إيقاف مؤقت" : "استئناف"}
                className={`absolute bottom-3 left-3 p-2 rounded-xl backdrop-blur-md border text-xs font-bold transition-all flex items-center gap-1.5 ${
                  isRecording
                    ? 'bg-black/60 hover:bg-black/80 text-amber-300 border-amber-500/40'
                    : 'bg-emerald-600 hover:bg-emerald-500 text-white border-emerald-400/50'
                }`}
              >
                {isRecording ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
                <span className="hidden sm:inline">{isRecording ? 'إيقاف مؤقت' : 'استئناف'}</span>
              </button>
            </div>

            {/* Location & Station inputs */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 p-3.5 rounded-2xl bg-slate-950 border border-slate-800">
              <div>
                <label className="block text-xs text-slate-400 mb-1">اسم الموقع / المحطة محل التوثيق</label>
                <input
                  type="text"
                  value={siteName}
                  onChange={(e) => setSiteName(e.target.value)}
                  className="w-full px-3 py-2 text-xs rounded-xl bg-slate-900 border border-slate-700 text-white focus:outline-none focus:border-emerald-500"
                />
              </div>
              <div>
                <label className="block text-xs text-slate-400 mb-1">المحافظة</label>
                <select
                  value={governorate}
                  onChange={(e) => setGovernorate(e.target.value)}
                  className="w-full px-3 py-2 text-xs rounded-xl bg-slate-900 border border-slate-700 text-white focus:outline-none focus:border-emerald-500"
                >
                  <option value="القاهرة">القاهرة</option>
                  <option value="الجيزة">الجيزة</option>
                  <option value="الإسكندرية">الإسكندرية</option>
                  <option value="القليوبية">القليوبية</option>
                  <option value="الشرقية">الشرقية</option>
                  <option value="الدقهلية">الدقهلية</option>
                  <option value="السويس">السويس</option>
                </select>
              </div>
            </div>
          </div>

          {/* Right Panel: Department Checklist & Session Controls (5 Cols) */}
          <div className="lg:col-span-5 flex flex-col justify-between gap-5">
            
            <div className="space-y-4">
              <div>
                <h4 className="text-sm font-bold text-white mb-1 flex items-center gap-2">
                  <Wrench className="w-4 h-4 text-emerald-400" />
                  <span>عناصر ومعدات الفحص المعتمدة ({meta.badge})</span>
                </h4>
                <p className="text-xs text-slate-400 mb-3">
                  حدد العناصر والآلات التي تم توثيقها ورفع حالتها بالكاميرا:
                </p>

                <div className="grid grid-cols-1 gap-2">
                  {getDepartmentEquipments().map((eq) => {
                    const isChecked = inspectedItems.includes(eq.label);
                    return (
                      <button
                        key={eq.id}
                        type="button"
                        onClick={() => toggleInspectedItem(eq.label)}
                        className={`p-2.5 rounded-xl border text-xs text-right font-medium transition-all flex items-center justify-between cursor-pointer ${
                          isChecked
                            ? 'bg-emerald-500/15 border-emerald-500/40 text-emerald-200'
                            : 'bg-slate-950/60 border-slate-800 text-slate-300 hover:border-slate-700'
                        }`}
                      >
                        <span>{eq.label}</span>
                        <div className={`w-4 h-4 rounded-md border flex items-center justify-center shrink-0 ${
                          isChecked ? 'bg-emerald-500 border-emerald-400 text-slate-950' : 'border-slate-700'
                        }`}>
                          {isChecked && <Check className="w-3 h-3 stroke-[3]" />}
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Notes */}
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1">
                  ملاحظات ونتائج التوثيق الفني للموقع:
                </label>
                <textarea
                  rows={3}
                  value={findingsNotes}
                  onChange={(e) => setFindingsNotes(e.target.value)}
                  placeholder="أدخل ملاحظات المعاينة، القراءات، أو تقرير الحالة الإنشائية والمعدات..."
                  className="w-full px-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-white text-xs placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 resize-none"
                />
              </div>
            </div>

            {/* Mandatory User Action Buttons: إيقاف مؤقت / إنهاء وحفظ / إلغاء الجلسة */}
            <div className="pt-4 border-t border-slate-800 space-y-2.5">
              <div className="text-[11px] text-slate-400 text-center mb-1">
                سيتم تخزين الفيديو في مخزن الرصد الميداني واستدعاؤه لدى المدير العام ومدير النظام
              </div>

              {/* Pause / Resume Button */}
              <button
                type="button"
                id="btn-dept-pause-resume"
                onClick={() => setIsRecording(!isRecording)}
                className={`w-full py-3 px-4 rounded-xl border text-xs font-bold transition-all flex items-center justify-center gap-2 cursor-pointer shadow-md ${
                  isRecording
                    ? 'bg-amber-500/15 hover:bg-amber-500/25 text-amber-300 border-amber-500/40 shadow-amber-500/10'
                    : 'bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 border-emerald-500/40 shadow-emerald-500/10'
                }`}
              >
                {isRecording ? (
                  <>
                    <Pause className="w-4 h-4 text-amber-400" />
                    <span>إيقاف الجلسة مؤقتاً (Pause)</span>
                  </>
                ) : (
                  <>
                    <Play className="w-4 h-4 text-emerald-400" />
                    <span>استئناف تسجيل الجلسة (Resume)</span>
                  </>
                )}
              </button>

              {/* Green Save & Finish Button */}
              <button
                type="button"
                id="btn-dept-save-finish"
                onClick={handleFinishAndSave}
                className="w-full py-3.5 px-4 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-bold text-sm shadow-lg shadow-emerald-600/30 hover:shadow-emerald-600/50 transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                <CheckCircle2 className="w-5 h-5 text-emerald-100" />
                <span>إنهاء وحفظ الجلسة وتخزين الفيديو</span>
              </button>

              {/* Red Cancel Button */}
              <button
                type="button"
                id="btn-dept-cancel-session"
                onClick={() => setShowCancelConfirm(true)}
                className="w-full py-2.5 px-4 rounded-xl bg-slate-800/80 hover:bg-rose-500/20 text-slate-300 hover:text-rose-300 border border-slate-700 hover:border-rose-500/40 text-xs font-semibold transition-all flex items-center justify-center gap-2 cursor-pointer"
              >
                <XCircle className="w-4 h-4 text-rose-400" />
                <span>إلغاء الجلسة دون حفظ</span>
              </button>
            </div>
          </div>
        </div>

        {/* Confirmation Modal for Cancel Saving */}
        {showCancelConfirm && (
          <div className="absolute inset-0 z-20 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-sm animate-fadeIn">
            <div className="w-full max-w-sm bg-slate-900 border border-rose-500/30 rounded-2xl p-6 text-center shadow-2xl">
              <div className="w-12 h-12 mx-auto rounded-xl bg-rose-500/10 border border-rose-500/30 flex items-center justify-center text-rose-400 mb-3">
                <AlertTriangle className="w-6 h-6" />
              </div>
              <h4 className="text-base font-bold text-white mb-1">
                تأكيد إلغاء حفظ الجلسة؟
              </h4>
              <p className="text-xs text-slate-400 mb-5 leading-relaxed">
                هل أنت متأكد من إلغاء حفظ جلسة الرصد؟ سيتم إغلاق الكاميرا دون تخزين الفيديو في الأرشيف المركزي.
              </p>
              <div className="flex items-center gap-3">
                <button
                  type="button"
                  onClick={handleCancelSaving}
                  className="flex-1 py-2.5 px-3 rounded-xl bg-rose-600 hover:bg-rose-500 text-white text-xs font-bold transition-all"
                >
                  نعم، إلغاء وعدم الحفظ
                </button>
                <button
                  type="button"
                  onClick={() => setShowCancelConfirm(false)}
                  className="flex-1 py-2.5 px-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold transition-all"
                >
                  متابعة التسجيل
                </button>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};
